####################################
# APPLICATION
####################################
buni.ambiente=HML

####################################
# FRONTEND
####################################
app.frontend.url=http://localhost:5180

####################################
# CORS
####################################
app.cors.allowed-origins=http://localhost:5180

####################################
# CLIENTES - Endpoints
####################################
buni.cliente.base-url=https://buncghml.funcao.digital/API/FIApiAutClientePF
buni.cliente.endpoint.incluir=/ClientePF/ClientePF_IncluirCliente
buni.cliente.endpoint.consulta=/ClientePF/ClientePorCPF

buni.cliente.inclusao.url=${buni.cliente.base-url}${buni.cliente.endpoint.incluir}
buni.cliente.consulta-cpf.url=${buni.cliente.base-url}${buni.cliente.endpoint.consulta}

####################################
# CLIENTES - Autenticacao
####################################
buni.cliente.auth.url=${buni.cliente.base-url}/oauth/token
buni.cliente.auth.client-id=${BUNI_CLIENT_ID:955000}
buni.cliente.auth.client-secret=${BUNI_CLIENT_SECRET:0000146828BAA0D2DC78FA4FA69E0CE586CB1E2D87}
buni.cliente.auth.grant-type=filicenca
buni.cliente.auth.username=${BUNI_USERNAME:USR_API}
buni.cliente.auth.password=${BUNI_PASSWORD:Buni@2026}

####################################
# FUNCIONARIOS - Endpoints
####################################
buni.funcionario.base-url=https://buncghml.funcao.digital/API/FIAPIEmprCadastroFunc
buni.funcionario.endpoint.cadastrar=/CadastroFuncionario/CadastrarFuncionarioEXT

buni.funcionario.cadastro.url=${buni.funcionario.base-url}${buni.funcionario.endpoint.cadastrar}

####################################
# FUNCIONARIOS - Autenticacao
####################################
buni.funcionario.auth.url=${buni.funcionario.base-url}/oauth/token
buni.funcionario.auth.client-id=${FUNC_CLIENT_ID:023000}
buni.funcionario.auth.client-secret=${FUNC_CLIENT_SECRET:0000146828BAA0D2DC78FA4FA69E0CE586CB1E2D87}
buni.funcionario.auth.grant-type=filicenca
buni.funcionario.auth.username=${FUNC_USERNAME:USR_API}
buni.funcionario.auth.password=${FUNC_PASSWORD:Buni@2026}
