####################################
# APPLICATION
####################################
buni.ambiente=HML

####################################
# FRONTEND / CORS
####################################
app.frontend.url=http://localhost:5176
app.cors.allowed-origins=http://localhost:5176

####################################
# CLIENTES - Endpoints
####################################
buni.cliente.base-url=https://buncghml.funcao.digital/API/FIApiAutClientePF
buni.cliente.endpoint.incluir=/ClientePF/ClientePF_IncluirCliente
buni.cliente.endpoint.consulta=/ClientePF/ClientePorCPF
buni.cliente.inclusao.url=${buni.cliente.base-url}${buni.cliente.endpoint.incluir}
buni.cliente.consulta-cpf.url=${buni.cliente.base-url}${buni.cliente.endpoint.consulta}

####################################
# CLIENTES - Autenticação
####################################
buni.cliente.auth.url=${buni.cliente.base-url}/oauth/token
buni.cliente.auth.grant-type=filicenca
buni.cliente.auth.client-id=${BUNI_CLIENT_ID}
buni.cliente.auth.client-secret=${BUNI_CLIENT_SECRET}
buni.cliente.auth.username=${BUNI_USERNAME}
buni.cliente.auth.password=${BUNI_PASSWORD}

####################################
# FUNCIONÁRIOS - Endpoints
####################################
buni.funcionario.base-url=https://buncghml.funcao.digital/API/FIAPIEmprCadastroFunc
buni.funcionario.endpoint.cadastrar=/CadastroFuncionario/CadastrarFuncionarioEXT
buni.funcionario.cadastro.url=${buni.funcionario.base-url}${buni.funcionario.endpoint.cadastrar}

####################################
# FUNCIONÁRIOS - Autenticação
####################################
buni.funcionario.auth.url=${buni.funcionario.base-url}/oauth/token
buni.funcionario.auth.grant-type=filicenca
buni.funcionario.auth.client-id=${FUNC_CLIENT_ID}
buni.funcionario.auth.client-secret=${FUNC_CLIENT_SECRET}
buni.funcionario.auth.username=${FUNC_USERNAME}
buni.funcionario.auth.password=${FUNC_PASSWORD}
