####################################
# APPLICATION
####################################
spring.application.name=integration-engine

# Perfil ativo padrão. Para sobrescrever use: -Dspring.profiles.active=dev|hml|prod
spring.profiles.active=hml

####################################
# SERVER
####################################
server.port=8080

####################################
# MULTIPART
####################################
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=-1

####################################
# CSV
####################################
# Charset para leitura do CSV. Alterar para ISO-8859-1 ou WINDOWS-1252
# se o sistema de RH exportar com encoding Latin.
buni.csv.charset=UTF-8
